version: '3'

services:

  packer:
    image: hashicorp/packer:light
    volumes:
      - ./:/app
    working_dir: /app

  terraform:
    image: hashicorp/terraform:light
    volumes:
      - ./:/app
    working_dir: /app
